# Generated by Django 6.1.1 on 2026-09-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nis', models.CharField(max_length=20, unique=True)),
                ('jk', models.CharField(max_length=10)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.TextField()),
                ('no_tlpn_wa', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('asrama', models.CharField(blank=True, max_length=100)),
                ('semester', models.PositiveIntegerField()),
                ('prodi', models.CharField(max_length=100)),
            ],
        ),
    ]
