# Generated by Django 6.1.1 on 2026-09-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nama_ayah',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
