# Generated by Django 6.1.1 on 2026-09-11 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_asrama'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='asrama_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.asrama'),
        ),
    ]
