# Generated by Django 6.1.1 on 2026-09-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_asrama_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='kelas',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
