# Generated by Django 6.1.1 on 2026-09-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='kelas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
