# Generated by Django 6.1.1 on 2026-09-12 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.kelas'),
        ),
    ]
