# Generated by Django 6.1.1 on 2026-09-12 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_kelas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='nis',
            new_name='nim',
        ),
    ]
