# Generated by Django 6.1.1 on 2026-09-12 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_rename_nis_student_nim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alpa', 'Alpa')], default='Hadir', max_length=10)),
                ('keterangan', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='students.student')),
            ],
            options={
                'ordering': ['-tanggal'],
                'constraints': [models.UniqueConstraint(fields=('student', 'tanggal'), name='unique_absensi_student_tanggal')],
            },
        ),
    ]
