# Generated by Django 6.1.1 on 2026-09-12 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_absensi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20, unique=True)),
                ('aktif', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('aktif', models.BooleanField(default=True)),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_pelajaran', to='students.tahunajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_harian', models.PositiveIntegerField(blank=True, null=True)),
                ('nilai_ujian', models.PositiveIntegerField(blank=True, null=True)),
                ('nilai_akhir', models.PositiveIntegerField(blank=True, null=True)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian', to='students.matapelajaran')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian', to='students.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'mata_pelajaran'), name='unique_penilaian_student_mapel')],
            },
        ),
    ]
