# Generated by Django 6.1.1 on 2026-09-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_tahunajaran_matapelajaran_penilaian'),
    ]

    operations = [
        migrations.AddField(
            model_name='matapelajaran',
            name='kelas',
            field=models.ManyToManyField(blank=True, related_name='mata_pelajaran', to='students.kelas'),
        ),
    ]
