# Generated by Django 6.1.1 on 2026-09-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_matapelajaran_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='matapelajaran',
            name='kitab',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
