# Generated by Django 6.1.1 on 2026-09-13 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_matapelajaran_kitab'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.tahunajaran'),
        ),
    ]
