# Generated by Django 5.1.5 on 2026-09-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_absensi_id_alter_asrama_id_alter_kelas_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'nama',
                    models.CharField(
                        max_length=150,
                        unique=True
                    )
                ),
            ],
            options={
                'verbose_name': 'Guru',
                'verbose_name_plural': 'Guru',
                'ordering': ['nama'],
            },
        ),

        migrations.CreateModel(
            name='PresensiGuru',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'tanggal',
                    models.DateField()
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('Hadir', 'Hadir'),
                            ('Izin', 'Izin'),
                            ('Sakit', 'Sakit'),
                            ('Alpa', 'Alpa'),
                        ],
                        default='Alpa',
                        max_length=10
                    )
                ),
                (
                    'keterangan',
                    models.TextField(blank=True)
                ),
                (
                    'guru',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='presensi',
                        to='students.guru'
                    )
                ),
            ],
            options={
                'ordering': ['-tanggal', 'guru__nama'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('guru', 'tanggal'),
                        name='unique_presensi_guru_per_tanggal'
                    )
                ],
            },
        ),
    ]