# Generated by Django 5.1.5 on 2026-09-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_guru_presensi_guru'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='jenis_kelamin',
            field=models.CharField(
                choices=[
                    ('L', 'Laki-laki'),
                    ('P', 'Perempuan'),
                ],
                default='L',
                max_length=1,
            ),
        ),
    ]