# Generated by Django 5.1.5 on 2026-09-19 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_guru_jenis_kelamin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatKelasSiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(blank=True, null=True)),
                ('tanggal_masuk', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riwayat_siswa', to='students.kelas')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_kelas', to='students.student')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riwayat_kelas_siswa', to='students.tahunajaran')),
            ],
            options={
                'verbose_name': 'Riwayat Kelas Siswa',
                'verbose_name_plural': 'Riwayat Kelas Siswa',
                'ordering': ['-tahun_ajaran', 'kelas__nama', 'student__nama'],
                'constraints': [models.UniqueConstraint(fields=('student', 'tahun_ajaran'), name='unique_student_tahun_ajaran')],
            },
        ),
    ]
