# Generated by Django 5.1.5 on 2026-09-19 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_riwayatkelassiswa'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='penilaian',
            name='unique_penilaian_student_mapel',
        ),
        migrations.AddField(
            model_name='penilaian',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penilaian', to='students.tahunajaran'),
        ),
        migrations.AddConstraint(
            model_name='penilaian',
            constraint=models.UniqueConstraint(fields=('student', 'tahun_ajaran', 'mata_pelajaran'), name='unique_penilaian_student_tahun_mapel'),
        ),
    ]
